[HighFive]
git-tree-sha1 = "3c29a7943feedafcf0a1e4f525015179d69bf918"

    [[HighFive.download]]
    sha256 = "c55a5e96b61e8a3565ccf2a725f44cdf23a431f05cd13fe7016d63afb0459fd4"
    url = "https://github.com/JuliaBinaryWrappers/HighFive_jll.jl/releases/download/HighFive-v3.2.0+0/HighFive.v3.2.0.any.tar.gz"
