# Autogenerated wrapper script for HighFive_jll for any
export highfive

using HDF5_jll
using boost_jll
JLLWrappers.@generate_wrapper_header("HighFive")
JLLWrappers.@declare_file_product(highfive)
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, boost_jll)
    JLLWrappers.@init_file_product(
        highfive,
        "include/highfive/highfive.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
